version: 2
sources:
  - name: gz_raw_data
    tables:
      - name: raw_gz_sales
        description: tableau des ventes
        loaded_at_field: CAST(date_date AS TIMESTAMP)
        freshness:
          warn_after: {count: 90, period: day}
        columns:
          - name: orders_id
          - name: pdt_id
          - name: date_date
        tests:
          - unique:
              column_name: "(orders_id || '_' || pdt_id)"
          - not_null:
              column_name: "(orders_id || '_' || pdt_id)"
      - name: raw_gz_product
        description: tableau des produits
        columns:
          - name: products_id
            tests:
              - unique
              - not_null
      - name: raw_gz_ship
        description: tableau des livraisons
        columns:
          - name: orders_id
            tests:
              - unique
              - not_null