version: 2
sources:
  - name: gz_raw_data
    tables:
      - name: raw_gz_sales
        description: tableau des ventes
        columns:
          - name: orders_id
            tests:
              - unique
              - not_null
      - name: raw_gz_product
        description: tableau des produits
        columns:
          - name: products_id
            tests:
              - unique
              - not_null
      - name: raw_gz_ship
        description: tableau des livraisons
        columns:
          - name: orders_id
            tests:
              - unique
              - not_null